apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-app.fullname" . }}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort}} # the port for client to access
      targetPort: {{ .Values.service.internalPort}} # the port that web server listen on
      protocol: TCP # TCP/UDP are available, default is TCP
      name: http
  selector:
    {{- include "spring-app.selectorLabels" . | nindent 4 }}
